all : InsertionSort
InsertionSort : InsertionSort.cpp InsertionSort.h
	g++ -o InsertionSort -g -Wall InsertionSort.cpp
	#g++ -ggdb3 -o InsertionSort -g -Wall InsertionSort.cpp
clean :
	rm -rf *.o InsertionSort *.dSYM
